blueprint:
  name: Turn On/off charging after device is reaches a certain level
  description: Turn on/off the smart plug/relay after the device is charged/disscharged to a given percent.
  domain: automation
  input:
    switch:
      name: Smart plug/relay
      description: Smart plug/relay to turn on/off charging
      selector:
        entity:
          domain: switch

    phone_battery:
      name: Phone Battery
      description: Battery level sensor
      selector:
        entity:
          domain: sensor
          device_class: battery

    charged_percent:
      name: Charge percent
      description: Charge device to this percent
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: "box"
      default: 90

	discharged_percent:
      name: Discharge percent
      description: Charge device from this percent
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: "box"
      default: 20

variables:
  phone_battery: !input phone_battery
  charged_percent: !input charged_percent
  discharged_percent: !input discharged_percent

trigger:
  - platform: state
    entity_id: !input phone_battery

action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ (states(phone_battery)|int) >= (charged_percent|int) }}'
    sequence:
    - service: switch.turn_off
      data: {}
      entity_id: !input 'switch'
  - conditions:
    - condition: template
      value_template: '{{ (states(phone_battery)|int) <= (discharged_percent|int) }}'
    sequence:
    - service: switch.turn_on
      data: {}
      entity_id: !input 'switch'
  default: []